# Generated by Django 5.0.8 on 2025-12-15 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('ai_mode', models.CharField(default='NONE', max_length=16)),
                ('provider', models.CharField(default='NONE', max_length=16)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
