# Generated by Django 5.0.8 on 2025-12-15 22:36

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='last_download_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_download_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_download_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='upload_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='upload_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.jobs.models.results_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='uploaded_file',
            field=models.FileField(upload_to=apps.jobs.models.uploads_path),
        ),
    ]
