# Generated by Django 5.0.8 on 2025-12-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_download_count_job_last_download_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UPLOAD', 'Upload'), ('CHECK_START', 'Check Start'), ('CHECK_DONE', 'Check Done'), ('CHECK_FAILED', 'Check Failed'), ('DOWNLOAD', 'Download'), ('DOWNLOAD_FAILED', 'Download Failed')], max_length=32)),
                ('ok', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
