# Generated by Django 5.0.8 on 2025-12-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobevent',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
