# Generated by Django 5.0.8 on 2025-12-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobevent_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
